version: "3"

services:
  proxy-service:
    image: onfinality/subql-indexer-proxy:v0.1.6-4
    container_name: proxy_server
    ports:
      - 8009:8009
    restart: always
    command:
      - --port=8009
      - --host==0.0.0.0
      - --secret-key=qmbyd5hwac2jdcu
      - --service-url=http://ec2-3-25-75-215.ap-southeast-2.compute.amazonaws.com:8000/graphql
      - --debug
      - --dev
networks:
  default:
    external:
      name: cooridnator-service
